# Generated by Django 3.2.4 on 2021-09-14 08:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('dataUpload', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='basicplotsclass',
            fields=[
                ('data_upload', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='dataUpload.task')),
                ('basic_plots', models.CharField(choices=[('cts_per_cell', 'counts per cell'), ('gen_per_cell', 'genes per cell'), ('cts_per_gen', 'counts per gene'), ('cells_per_gen', 'cells per gene'), ('gen_per_cell_ord', 'gene per cell (Ordered)'), ('mito_cont', 'mitochondrial content')], default='cts_per_cell', max_length=30)),
            ],
        ),
    ]
