# Generated by Django 3.2.4 on 2021-09-13 17:41

import dataUpload.models
from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Task',
            fields=[
                ('file_id', models.AutoField(primary_key=True, serialize=False)),
                ('task_id', models.UUIDField(default=uuid.uuid4, editable=False)),
                ('file', models.FileField(upload_to=dataUpload.models.task_directory_path)),
                ('path_to_tar', models.CharField(default='', max_length=1000)),
                ('path_to_cache', models.CharField(default='', max_length=1000)),
            ],
        ),
    ]
